# test deploy in kubernates

trigger:
  - None

pool:
  vmImage: ubuntu-latest
variables:
  ACR.Name: 'ainhabacr'
  Azure.ServiceConnection: 'ainhabacrconnection'
steps:
  - task: HelmInstaller@0
    displayName: 'installHelm'
    inputs:
      helmVersion: 3.9.3
      kubectlVersion: 1.26.3
  - task: HelmDeploy@0
    displayName: 'helm uninstall'
    continueOnError: true
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: 'ainhab-blue'
      namespace: 'blue'
      command: 'uninstall'
      chartType: Name
      chartName: 'oci://$(ACR.Name).azurecr.io/charts/bpwebapp'
      releaseName: bpwebapp
      waitForExecution: false
      force: true
      upgradetiller: false
      save: false
      install: false
      arguments: bpwebapp
    
  - task: HelmDeploy@0
    displayName: 'helm uninstall'
    enabled: false
    continueOnError: true
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: 'ainhab-green'
      namespace: 'green'
      command: 'uninstall'
      chartType: Name
      chartName: 'oci://$(ACR.Name).azurecr.io/charts/bpwebapp'
      releaseName: bpwebapp
      waitForExecution: false
      force: true
      upgradetiller: false
      save: false
      install: false
      arguments: bpwebapp

