{{- if .Values.golive -}}
kind: Service
apiVersion: v1
metadata:
  name: service-live
  namespace: default
spec:
  type: ExternalName
  externalName: bpfesvc.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - port: 32137
{{- end -}}