apiVersion: "v1"
kind: "Secret"
metadata:
  name: "mongo-secrets"
type: "Opaque"
data:
  MONGO_USERNAME: bW9uZ28K
  MONGO_PASSWORD: MWYyZDFlMmU2N2RmCg==
  MONGO_CREDENTIAL: bW9uZ286MWYyZDFlMmU2N2RmCg==
#  mongo:1f2d1e2e67df
