apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-ainhab-serviceaccount
subjects:
- kind: ServiceAccount
  name: ainhab-serviceaccount
roleRef:
  kind: Role
  name: role-for-ainhab-serviceaccount
  apiGroup: rbac.authorization.k8s.io