apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: mongodb-app
  labels:
    app: mongodb
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  # pod template
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # pod contains 1 container
      containers:
      - image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
