trigger: none

pool:
  vmImage: ubuntu-latest

steps:

  #   Mongo DB Image will be downloaded from Docker Hub

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'MongoSvcConn'
      namespace: 'mongo'
      command: 'apply'
      arguments: '-f $(Build.SourcesDirectory)/mongodb/mongodb-mongodb-deployment.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'