kind: Service
apiVersion: v1
metadata:
  name: service-blue
spec:
  type: ExternalName
  externalName: bpfesvc.blue.svc.cluster.local
  ports:
    - port: 32137
---
kind: Service
apiVersion: v1
metadata:
  name: service-green
spec:
  type: ExternalName
  externalName: bpfesvc.green.svc.cluster.local
  ports:
    - port: 32137
