trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: KubectlInstaller@0
    inputs:
        kubectlVersion: '1.26.3'
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
      azureResourceGroup: 'k8s-resource-group'
      kubernetesCluster: 'ainhabAKSCluster'
      command: 'apply'
      useConfigurationFile: true
      configuration: '$(Build.SourcesDirectory)/LoadBalancer/bp-ingress-loadbalancer.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'