apiVersion: v1
kind: Service
metadata:
  name: bp-webapp-main-service
spec:
  type: ExternalName
  externalName: bpfesvc.blue.svc.cluster.local
  ports:
  - port: 27017
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bp-web-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: bp-webapp-main-service
                port:
                  number: 27017