# build docker
# publish to container registry
# build helm
# publish to helm repo

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - None

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bc2aadcc-1517-44b8-9314-ea3f6c496a86'
  imageRepository: 'eadca2/reverse-proxy'
  containerRegistry: 'ainhabacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/nginx/Dockerfile'
  azureACRSubscription: '7263e463-da66-4888-a897-f34f5acea14b'
  azureACRResourceGroup: 'k8s-resource-group'
  ACR.Name: 'ainhabacr'
  tag: 'v1'


steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      buildContext: $(Build.SourcesDirectory)/nginx
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az acr login --name $(ACR.Name)'
  - task: KubectlInstaller@0
    displayName: 'Install Kubectl 1.26.3'
    inputs:
      kubectlVersion: 1.26.3
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'default-svc-conn'
      namespace: 'default'
      command: 'apply'
      arguments: '-f $(Build.SourcesDirectory)/nginx-deployment.yaml --timeout=30s'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'