apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - image: ainhabacr.azurecr.io/eadca2/reverse-proxy:v1
        imagePullPolicy: Never
        name: bpwebapp-proxy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: reverse-proxy
