dependencies:
  #  - name: bpdataservice
  #    repository: file://charts/bp_data_service-1.0.0.tgz
  #    version: 1.0.0
  - name: bbinfoservice
    repository: oci://ainhabacr.azurecr.io/charts/bpinfoservice
    vesion: 1.0.0
#  - name: bprecordingservice
#    repository: file://charts/bp_recording_service-1.0.0.tgz
#    vesion: 1.0.0
#  - name: bpuiservice
#    repository: file://charts/bp_ui_service-1.0.0.tgz
#    version: 1.0.0
