# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest


steps:

  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: '1.25.4'

  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.14.1'
      installKubectl: true
#
#  - task: AzureCLI@2
#    inputs:
#      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
#      scriptType: 'bash'
#      scriptLocation: 'inlineScript'
#      inlineScript: |
#        az account set --subscription 7263e463-da66-4888-a897-f34f5acea14b
#
#  - task: AzureCLI@2
#    inputs:
#      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
#      scriptType: 'bash'
#      scriptLocation: 'inlineScript'
#      inlineScript: |
#        az aks get-credentials --resource-group k8s-resource-group --name ainhabAKS

   - task: AzureCLI@2
     inputs:
       azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
         helm repo update

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
      azureResourceGroup: 'k8s-resource-group'
      kubernetesCluster: 'ainhabAKS'
      namespace: 'ingress-nginx'
      command: 'upgrade'
      chartType: 'Name'
      chartName: 'ingress-nginx/ingress-nginx'
      releaseName: 'ingress-nginx'
      arguments: '--install'

